### ISSUE TITLE
Add support for Deezer

### ISSUE THREAD

**Issue by brunomiguel** [tizonia/tizonia-openmax-il#294]
Could you add support for Deezer? It's a streaming service similar to Spotify.

**Comment by juanrubio** [comment]
Hi Bruno,

I briefly tried Deezer in the past, on mobile. But never looked at its API. I've noticed that there is a free tier and that some open source projects have Deezer integrations (like Mopidy). 

So it should not be too difficult. I have other things in the pipeline right now, but I might push the skeleton for a future 'libtizdeezer' (C lib) and 'deezerproxy' (Python) modules, in case someone might want to help (maybe you know some Python? :-) )

**Comment by brunomiguel** [comment]
Sadly, I don't know Python :(

**Comment by juanrubio** [comment]
Closing this now. This is already implemented. Binaries for a new release of Tizonia with Deezer support should become available this week or next.

**Comment by muzzol** [comment]
Can this issue be reopened?
due tu bug https://github.com/tizonia/tizonia-openmax-il/issues/360 support has been dropped.

I'm not sure about current legal status, but maybe an alternative method without private encryption keys can be found.

**Comment by tizonia** [comment]
Hi!, thanks for showing interest. 

I've got plans to extend the number of music services that can be supported, including Deezer, and Pandora, this time using a different approach. I will be looking at providing a compatibility layer that might allow reusing existing Mopidy plugins, since there is already a huge community behind them. But that will after Chromecast support is out of my way.
