### ISSUE TITLE
"Illegal instrunction" on "2017-07-05-raspbian-jessie-lite.img"

### ISSUE THREAD

**Issue by tahiro86j** [tizonia/tizonia-openmax-il#372]
Shows an error message as in the title, at the end of curl-bash method for installation and when attempting to launch the program. I'm not exactly a programmer-guy, so please first let me know if there are any specific instructions on preferred methods for reproducing the condition to obtain the screen-output that you may be interested in.
FYI, screenshot I've managed to capture is posted [here](https://twitter.com/tahiro86j/status/913917534759297025).

**Comment by tizonia** [comment]
Sorry to hear that. Unfortunately, Tizonia's Raspbian images only work on the Raspberry pi 2 and 3. They won't work on the 1 or 0 since they have the older armv6 cpu.

I think at some point, I had the intention to produce images for armv6 rpis but it kind of fell through the cracks.

Let's leave this bug open since the README.md should really explain this. Also I think I'll get those images built one of these days.

**Comment by juanrubio** [comment]
All right, it looks like I finally found the recipe that will produce the armv6-compatible packages.
See:
- https://www.raspberrypi.org/forums/viewtopic.php?f=33&t=195802&p=1225055#p1225055

I'm releasing v0.10.0 this weekend and i think this will be the first release that works on pi zero and other armv6 pis.

**Comment by juanrubio** [comment]
I believe this is fixed so I'm closing for now. 

v0.10.0 binaries will be available from tonight, so we will re-open if necessary.
