### ISSUE TITLE
Binary for Ubuntu 17.10

### ISSUE THREAD

**Issue by haideralipunjabi** [tizonia/tizonia-openmax-il#389]

**Comment by juanrubio** [comment]
Hi, thanks for showing interest!

At the moment, there are no 17.10 binaries. The reason is I usually tend to disregard the .10 releases due to their short lifespan, but the ultimate reason being that producing binaries for every Ubuntu release and/or flavor is highly time consuming, so I tend to restrict to the LTSs mostly.

The longer term fix that I have planned for this problem is to make available a Tizonia Snap package, through the snap store. That will hopefully be able to get Tizonia installed in way more Ubuntu releases and other Linux distros.

Please watch #309 for more news on this.

**Comment by haideralipunjabi** [comment]
I tried to build it from source, but encountered the following error

`configure.ac:21: warning: unknown warning category 'extra'
configure.ac:20: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:41: error: possibly undefined macro: AM_CONDITIONAL
autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Comment by juanrubio** [comment]
I think this is a configuration error. Have you installed all the dependencies?. E.g. when I install a fresh OS, I run this a couple of times in a row:
```
$ tizonia-dev-build --deps
```

Sometimes, I've noticed that the first time won't get all the dependencies installed. 

See this. The configuration phase succeeds as long as the dependencies are installed. But the compilation will fail, I believe because of a backward incompatible change (in dbuscxx  I believe, i'm still investigating)
```
https://github.com/tizonia/tizonia-openmax-il/issues/393#issuecomment-346935500
```

**Comment by juanrubio** [comment]
Hi @haideralipunjabi !

I'm closing this issue as we are tracking the main problem in #393. Please watch the progress of this in that other issue.
