### ISSUE TITLE
libspotify is deprecated

### ISSUE THREAD

**Issue by luigino** [tizonia/tizonia-openmax-il#395]
[Important! LibSpotify and CocoaLibSpotify are no longer under active development on any platform and are considered deprecated.
...
Please note that we have removed the LibSpotify binaries from our website in an effort to phase out the usage of this deprecated library. LibSpotify has been considered deprecated since 2015 and will be shut down in 2017](https://developer.spotify.com/technologies/libspotify)

Are there plans to do without it?

**Comment by juanrubio** [comment]
Hi!,

Great question. Yes, libspotify has been deprecated since 2015. There are plans to support Spotify via other means. The current plan is to support it by leveraging the great work that the Mopidy community has produced in the last few years. 

See https://github.com/tizonia/tizonia-openmax-il/issues/294#issuecomment-342446649

The goal is not to create a Mopidy clone out of Tizonia, but to open the possibility to reuse some of its cloud music plugins, whenever that makes sense. I think Spotify is one of those cases where that compatibility layer would make sense.

**Comment by luigino** [comment]
I see.

Meanwhile, since I'm packaging for openSUSE, is there a clean way to disable the Spotify plugin?

**Comment by juanrubio** [comment]
Understood. OpenSUSE, that's really cool. 

At the moment there isn't but it can be implemented very quickly. I've raised an issue for this: #396. I can get that implemented later this coming week, or if you are interested, you are more than welcome to submit a PR.

**Comment by juanrubio** [comment]
@luigino 

#396 is implemented now. 

Quoting from Building.md:

The `--without-libspotify` option may be included to disable configuration and
build of the libspotify-based OpenMAX IL component. This option will also
disable the support for this plugin in the `tizonia` player program.

```bash

   # Disable support for the spotify_source plugin.
   $ ./configure --without-libspotify

```

**Comment by juanrubio** [comment]
I hope this helps. And please let me know of any issues.
