### ISSUE TITLE
Can't install on Ubuntu 14.04 trusty

### ISSUE THREAD

**Issue by bjoernh** [tizonia/tizonia-openmax-il#398]
When i try to install tizonia on a old machine it fails with following error message:

> The following packages have unmet dependencies:
>  tizonia-all : Depends: python-tizsoundcloudproxy but it is not installable
>                Depends: python-tizdirbleproxy but it is not installable

So i looked at http://dl.bintray.com/tizonia/ubuntu/dists/trusty/main/binary-i386/:Packages and there is no python-tizsoundcloudproxy and python-tizdirbleproxy package available.

**Comment by juanrubio** [comment]
Hi!, 

are you perhaps on a 32-bit version of Ubuntu?. This could be the problem. I've stopped supporting 32-bit distros last year, since around this release:
https://github.com/tizonia/tizonia-openmax-il/releases/tag/v0.5.0

All distros are discontinuing their 32-bit releases, so I decided to stop building 32-bit packages (saves me a lot of time! :-) ).

If this is the case, and you have a bit of time in your hands, you can build Tizonia yourself. See
- tizonia-openmax-il/BUILDING.md

**Comment by bjoernh** [comment]
Thanks for the quick reply. :+1:  You are correct, my old machine is running a 32 bit Ubuntu. Now i see the hint on the readme (amd64, armhf).
