### ISSUE TITLE
Building tizonia on Ubuntu 17.10 Artful

### ISSUE THREAD

**Issue by bjoernh** [tizonia/tizonia-openmax-il#421]
Hi,
i had successful build tizonia on Ubuntu 17.10. I run only into one error that says something like can't find _mediainfo_ package. So installing **libmediainfo-dev** had fixed the Problem for me.
Maybe you can add it to the dependency list of the buildscript.
By the way: really nice tool!

**Comment by juanrubio** [comment]
Hi!,

Thanks for reminding me. Yes, I've also noticed this while building on 17.10 and 18.04. libmediainfo-dev is there in the dependency list of the build script, but for some reason it fails to install in those system. I believe there is some dependency clash with the various flavors of SSL that libcurl can be built against. And for some reason, this issue is not there in Ubuntus < 17.10.

I'll have a look to see if I can workaround it in the build script.
