### ISSUE TITLE
Unable to run on Solus OS

### ISSUE THREAD

**Issue by Abhinav1217** [tizonia/tizonia-openmax-il#434]
I installed Snap package for tizonia in solus. It gives me following error
```
abhinav@abhinav-solus ~ $ tizonia --help youtube
2018/01/16 01:09:06.705207 cmd_run.go:446: WARNING: cannot create user data directory: cannot read symlink: readlink /home/abhinav/snap/tizonia/current: invalid argument
tizonia 0.11.0. Copyright (C) 2017 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

```

I found that default location on solus os for snap is not `/var/lib/snap......` like what you mentioned in your readme. I had to copy config file from its installed location which I found through `locate` command.
```
abhinav@abhinav-solus ~ $ locate tizonia.conf
/snap/tizonia/15/etc/xdg/tizonia/tizonia.conf
```
so I edited your copy command to copy this file. But still I am getting same error. 
how do I edit the symlink here??

**Comment by tizonia** [comment]
Hi!,

Thanks for trying Tizonia in Solus.

> 2018/01/16 01:09:06.705207 cmd_run.go:446: WARNING: cannot create user data directory: cannot read symlink: readlink /home/abhinav/snap/tizonia/current: invalid argument

Looking at this, I tend to think that this issue is not related to Tizonia. Sounds like a 'Snapd'  integration issue in Solus. 

Would you be able to provide details of which version of snapd is installed on your system?

There is another good point in your report. And that is the fact that copying the tizonia.conf template from the snap installation folder into the user's snap home folder is quite a chore. Snaps are not installed in the same location in all the distros. So I think I will end up adding some logic to the program to generate the tizonia.conf file automatically on the first run, to spare this confusion to the users. It is not a great experience right out of the gate to have to locate this file in the file system to then copy it to some strange snap subdir in your $HOME.

**Comment by tizonia** [comment]
Thanks!, I've posted your question on the Snapcraft forum. 
https://forum.snapcraft.io/t/solus-os-cmd-run-go-446-warning-cannot-create-user-data-directory/3547

Definitely, the best solution here is to generate the file directly on the app's first run, if it does not exist in the expected location. I think the application has access to Snapd environment variables that will make provide the information on where this file is located in every system. 

I think I'll create a separate issue for that.

**Comment by juanrubio** [comment]
@Abhinav1217, would you be able to continue the conversation in the Snapcraft forum?

See https://forum.snapcraft.io/t/solus-os-cmd-run-go-446-warning-cannot-create-user-data-directory/3547

**Comment by Abhinav1217** [comment]
Yes I created an account on snapcraft just now and replied there. Thanks for posting it there. I hope I get some solution there.

**Comment by tizonia** [comment]
@Abhinav1217 : The master branch now will create a tizonia.conf file on first launch, if one does not exist. A new release will be out in the next few days. So I'm closing this for now. Thanks.
