### ISSUE TITLE
Google Music: '--gmusic-unlimited-station': random station playing

### ISSUE THREAD

**Issue by SolarAquarion** [tizonia/tizonia-openmax-il#522]
I'm doing 'tizonia --gmusic-unlimited-station "Fleshgod Apocalypse"' but it keeps on playing random staations

**Comment by SolarAquarion** [comment]
Stations are playing but it's not playing the songs i expect

**Comment by tizonia** [comment]
Hi!,

Thanks for reporting this. 

I've seen this strange behaviour before, but not sure how recently, perhaps right after gmusicapi 11.0.4 which was released a couple of days ago or even before that, not entirely sure.

Luckily the fix is in 7bdb42e, in the develop branch. A new version of Tizonia will be released in the next few days with this fix.
