### ISSUE TITLE
soundcloud-users-likes: OMX.Aratelia.audio_source.http:port:0 

### ISSUE THREAD

**Issue by letshin** [tizonia/tizonia-openmax-il#576]
# Issue Template

### Description
Just installed Tizonia on Raspbian

Running tizonia --soundcloud-user-likes returns the following error

```
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[SoundCloud] [Connecting] : '3-154538-619141167-************'.
[SoundCloud] (KeyError) : 

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```
The same issue persists for --soundcloud-user-streams but works for, --soundcloud-genres jazz without issue.

I read that this error may have to do with an outdated python library, in a previous issue. I have updated all python scripts but this issue still happens.

Thanks!

### Steps to Reproduce

1. tizonia --soundcloud-user-streams

**Expected behavior:** To play likes/streams from soundcloud

**Actual behaviour:** Error message apears

**Reproduces how often:** Everytime

### Versions
```
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_62]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v0.7.91]

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
### Installation Method Used
First: 
```
http://tizonia.org/docs/debian/
```

then reinstalled following:
```
https://bintray.com/tizonia/raspbian/tizonia-stretch
```
### Additional Information
N/A

**Comment by tizonia** [comment]
Hi!, thanks for taking some time to report an issue. 

I can't see this issue with any of my two SoundCloud accounts. I believe this may be happening because you have not liked any songs yet in SoundCloud with your current user? In this case, it is possible that tizonia is simply reporting that there are no songs in the lists returned by SoundCloud. 

If this is the case, the reporting of this error condition would need some improvements.

```
export TIZONIA_SOUNDCLOUDPROXY_DEBUG=1
```

If you export this variable and then re-run the same commands, there will be additional logs that would give us a better idea of where this error condition is being hit:

Would you be able to throw those debug logs into a file and drag the file into this issue? I will be looking at them. Thanks!

**Comment by letshin** [comment]
HI, sorry for the delayed response - have been busy in the pre-Easter season. I've actually 'liked' a playlist before this, but no songs, that led up to the error.

I've exported the variable - can you let me know where the logs are stored please?

**Comment by juanrubio** [comment]
Yes, as soon as you export the variable, tizonia will output debug info
from the soundcloud client module directly in the console. Just remember to
export the variable in the same shell window. Thanks!

**Comment by letshin** [comment]
OK, here it is. There wasn't much text so I thought that there wasn't any difference.
[TIZONIA_LOG.txt](https://github.com/tizonia/tizonia-openmax-il/files/3119076/TIZONIA_LOG.txt)

**Comment by tizonia** [comment]
Hi @letshin !

Thanks for uploading the logs.

I've committed a fix (c31e5c9) to improve the error reporting. Since you had not favorited any tracks, SoundCloud was not returning any results. It will be clearer now when SoundCloud returns nothing useful in any of the various SoundCloud search functions.

It will be released with v0.19.0.

**Comment by Frozen-byte** [comment]
I provide the requested logs using edge snap package on Kubuntu 19.10:
```
> tizonia --soundcloud-user-stream
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[SoundCloud] [Connecting] : '3-154538-***snip***'.
[2020-01-15 15:29:53,598] [ INFO] [140644521813760] [tizsoundcloudproxy:enqueue_user_stream:170] - enqueue_user_stream
[2020-01-15 15:29:53,602] [DEBUG] [140644521813760] [connectionpool:_new_conn:959] - Starting new HTTPS connection (1): api.soundcloud.com:443
[2020-01-15 15:29:53,756] [DEBUG] [140644521813760] [connectionpool:_make_request:437] - https://api.soundcloud.com:443 "GET /me/activities?offset=0&oauth_token=3-154538-***snip***&client_id=***snip*** HTTP/1.1" 200 3014
[SoundCloud] (TypeError) : argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/snap/tizonia/318/lib/python3.6/site-packages/tizsoundcloudproxy.py", line 171, in enqueue_user_stream
    stream_resource = self.__api.get('/me/activities', offset=0)
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/resource.py", line 69, in wrapped_resource
    result.collection = ResourceList(result.collection)
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/resource.py", line 46, in __init__
    data = [Resource(resource) for resource in resources]
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/resource.py", line 46, in <listcomp>
    data = [Resource(resource) for resource in resources]
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/resource.py", line 20, in __init__
    self.origin = Resource(self.origin)
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/resource.py", line 19, in __init__
    if hasattr(self, 'origin'):
  File "/snap/tizonia/318/lib/python3.6/site-packages/soundcloud/resource.py", line 32, in __getattr__
    if name in self.obj:
TypeError: argument of type 'NoneType' is not iterable

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

**Comment by tizonia** [comment]
@Frozen-byte 

Thanks for providing the logs, and apologies, this has fallen through the cracks!

I noticed that you were using the 0.19.0 Snap from the edge channell. I actually never released this into the stable channel because I think it was broken. So Snap stable is at 0.18.0 still (I'm planning to fix that soon)...

Coming back to the error reported when using `tizonia --soundcloud-user-stream`. What I think it's happening is simply that the user stream is empty. 

When I go to the SoundCloud Web app, I see this in my user stream:

```
Hear the latest posts from the people you’re following:
Your stream is currently empty. Go to Search or Home to find music & audio to listen to.
```

So effectively, using `--soundcloud-user-stream` returns nothing. Note in this log the empty collection returned `'collection': [],`

```
tizonia --soundcloud-user-stream 
tizonia 0.20.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[SoundCloud] [Connecting] : '1-154538-xxxx'.
[2020-02-26 22:46:40,943] [ INFO] [140479915153152] [tizsoundcloudproxy:enqueue_user_stream:232] - enqueue_user_stream
[2020-02-26 22:46:40,946] [DEBUG] [140479915153152] [connectionpool:_new_conn:959] - Starting new HTTPS connection (1): api.soundcloud.com:443
[2020-02-26 22:46:41,036] [DEBUG] [140479915153152] [connectionpool:_make_request:437] - https://api.soundcloud.com:443 "GET /me/activities?offset=0&oauth_token=1-154538-xx&client_id=xxx HTTP/1.1" 200 115
<soundcloud.resource.Resource object at 0x7fc407fe70f0>
{'collection': [],
 'future_href': 'https://api.soundcloud.com/me/activities?limit=10',
 'next_href': None}
[SoundCloud] (KeyError) : 
Traceback (most recent call last):
  File "/home/joni/temp/lib/python3.6/site-packages/tizsoundcloudproxy.py", line 257, in enqueue_user_stream
    raise KeyError
KeyError

tizonia exiting (OMX_ErrorInsufficientResources).

**Comment by tizonia** [comment]
So the fix here is to added better error reporting, to convey to the user what it is really happening:

e.g.:

```
$ tizonia --soundcloud-user-stream 
tizonia 0.20.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[SoundCloud] [Connecting] : '1-154538-xxx'.
[SoundCloud] (RuntimeError) : The user stream is empty

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```
