### ISSUE TITLE
youtube-audio-mix-search not playing song mentioned in search string

### ISSUE THREAD

**Issue by anirudh-ms-kumar** [tizonia/tizonia-openmax-il#581]
The youtube-audio-mix-search is not playing the song mentioned in the search string. 
Instead it plays a random stream. Does anyone know how to solve this issue?

P.S : The preview gif in tizonia.org seems to be working fine. However a similar search with a different argument("Mike Posner Pill in Ibiza" to be accurate) on tizonia plays a random stream

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to raise an issue.

yes, I think there are some mix searches that end up producing some odd playlists, where the specified song is not available at all in the resulting playlist. 

I'm not sure right now what causes it, my guess is that it is potentially a limitation on the APIs used by Tizonia (we use pafy which in turn uses youtube-dl) since this feature was kind of artificially crafted. I seem to remember that there was no API in pafy to obtain these 'mix' playlists. But I'm talking by memory and that was a long time ago.

I will recheck and come back.

**Comment by anirudh-ms-kumar** [comment]
Thanks for responding. Sure- once you know what the issue is lemme know.
And btw- great project!
