### ISSUE TITLE
YouTube Audio Steam Token Parameter

### ISSUE THREAD

**Issue by gdoerksen** [tizonia/tizonia-openmax-il#584]
# Issue Template

### Description

[youtube audio stream token parameter]

### Steps to Reproduce

1. [tizonia --youtube-audio-stream https://www.youtube.com/watch?v=7JqKRqOmzi0]

**Expected behavior:** [Steam youtube audio. This command has worked for me before. I also tried running other videos from youtube and they produce a similar error]

**Actual behaviour:** [Included here is the output I get from terminal: 

tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

ERROR: 7JqKRqOmzi0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[YouTube] (IOError) : ERROR: 7JqKRqOmzi0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
]

**Reproduces how often:** [100%]

### Versions

tizonia 0.18.0.
Debug Info:
            * [Boost 1_65_1]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v17.12]

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

curl -kL https://github.com/tizonia/tizonia-openmax-il/raw/master/tools/install.sh | bash

### Additional Information
This command was working fine for me and then suddenly one day I started getting this error on any youtube stream I attempted. 

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Psycoguana** [comment]
This is an error with youtube-dl. It's been fixed already.
Does anyone know if it's necessary to update tizonia or the individual youtube-dl package?

I tried `pip3 install youtube-dl --ignore-installed --upgrade`, it's been upgraded correctly to 2019.4.24, but it's still not working.

**Comment by tizonia** [comment]
Hi!, thanks very much for raising this.

Apparently, there has been some temporary issue, which is already fixed in the most recent youtube-dl:
https://github.com/mps-youtube/pafy/issues/168#issuecomment-486181541

I update Tizonia's Python dependencies on my systems pretty much on a daily basis. I think because of that I have not noticed the problem at all.

For users running a Debian installation of Tizonia, my recommendation is to frequently upgrade these dependencies. It tends to minimize this kind of occurrence:
https://github.com/tizonia/tizonia-openmax-il#upgrade-debian--ubuntu--raspbian

For users running the snap version of Tizonia, a new version of the snap needs to be spun in the Snapcraft build service. I've just done that a few moments ago.

So just to clarify, this works for me on my debian-based installation of Tizonia:
```
tizonia --youtube-audio-stream https://www.youtube.com/watch\?v\=7JqKRqOmzi0
```
and it should work also with the new version of the snap that will be available in the repos in the next couple of hours.

**Comment by Psycoguana** [comment]
I removed the Tizonia snap and re-installed using curl (before seeing this), and is working now. Thanks for answering so quickly tho!

**Comment by tizonia** [comment]
@Psycoguana 

Thanks, the snap packages have been rebuilt and are now in the snap repos, so I expect this to be fixed for the snap users as well.

Closing this issue now
