### ISSUE TITLE
Colored output options?

### ISSUE THREAD

**Issue by driador** [tizonia/tizonia-openmax-il#586]
Greetings!

Is there any way to change, or configure, the default output's color?  I can't seem to find any documentation to that end.  If not, that would be a great option for an enhancement.

Thank you

**Comment by tizonia** [comment]
Hi!, thanks for dropping by.

I think this is a great idea!. At the moment there is no way of externally configuring the existing color scheme. But it would be really nice if this could be done.

I don't have the time for this right now. It is not difficult to implement. I would be more than happy to provide guidance if someone wanted to contribute towards this!.

**Comment by driador** [comment]
I'd be willing to give this a crack, but I will need some direction.

**Comment by driador** [comment]
Bump.

**Comment by tizonia** [comment]
@driador 

Apologies for such a delayed reply. I wanted to get back to you once I had done enough research to provide you with sufficient info to get you on the right footing, and I've just struggled because of lack of time. 

Nonetheless, here is what I've got so far:
- Tizonia currently make use of the following ANSI color definitions, see [libtizplatform/src/tizprintf.h](https://github.com/tizonia/tizonia-openmax-il/blob/9004bc40b89eeafb04b28fbb2b772e47dd62fdc9/libtizplatform/src/tizprintf.h#L37):
```
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
#define KWHT "\x1B[37m"
```
This is used in C and C++ code, using simple macros like this one (see them further down in the same file):
```
#define TIZ_PRINTF_RED(format, args...) \
  tiz_printf (KRED, NULL, -1, NULL, format, ##args);
```

Note that the Python code does not use this mechanism. It will be necessary to handle the colors in that code in a separate way (we can leave that for later on, once we have worked out the scheme for configuring user colors via Tizonia config file).

So in Tizonia's config file, we could handle the user configuration like this (just a simple example):
```
[global]
color-theme = C1:RED,C2:GRN,C3:YEL,C4:BLU,C5:MAG,C6:CYN,C7:WHT
```

Here I'm adding a new namespace that currently does not exist, but I think would be useful: `[global]`
and provide a new set of macros, like this one:
```
#define TIZ_PRINTF_C1(format, args...) \
  tiz_printf (KC1, NULL, -1, NULL, format, ##args);
```

where KC1, KC2, etc could be just indices on a table of colors that would be initialized with the color information read from config file when the application is started.

I think this would work and would allow us to customize the 7 colors that are currently used throughout the application. However, that is not sufficient to allow customization of elements in the UI that contain a background color, like Tizonia's progress bar and the current track time indicator (these elements' colors are hacked directly in the code that handles those elements, we can fix that later). 

So this way of spec'ing the theme would need to be extended to include those elements as well.  
Still, I think the system I've just described is a bit limiting. Perhaps it would be good to allow the user to provide the ANSI escape sequences directly, rather than some mnemonic of one of the internally supported ANSI escape sequences.     

I have created a new branch off of master for this development since this will require many small changes here and there. Please feel free to use this branch for your pull requests, it is called `color-themes`. 

These are just some ideas to get things kick-started but I believe this can be improved. So please feel free to provide your own ideas, to improve or change as you see fit.

**Comment by tizonia** [comment]
This feature is now part of 0.20.0.
