### ISSUE TITLE
IS AWESOME WM SOLVED?

### ISSUE THREAD

**Issue by kanando** [tizonia/tizonia-openmax-il#616]
HI.
I was having problems with Tizonia in my archlinux with Awesome WM, with no desktop environment. After reading information in this page, I did not find any solution to the problem.
But after using the command:
$ pulseaudio --start
now Tizonia work without problem.
The original problem was solved?
I take the opportunity to ask about this error:
"/usr/lib/python2.7/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')"
it error appears at the beginning of tizonia, but it works anyway. 
link of my pc running tizonia in my Awesome WM, it shows the error and the fact than python-levenshtein is already installed:
https://ibb.co/r0sc8C9

**Comment by tizonia** [comment]
Hi!, thanks for your using Tizonia and for taking the time to ask questions. And apologies for such a late reply!

> The original problem was solved?

To be honest, I'm not sure what problem you are referring about. There is an issue with snap installations of Tizonia in Awesome WM (and in general, any Window Manager that is not Gnome). This problem had to do with some limitations in the snapd infrastructure, not a problem with the snap packaging of Tizonia. As far as I know, this problem is not solved. Are you referring to this?. 

> I take the opportunity to ask about this error:
> "/usr/lib/python2.7/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python
> SequenceMatcher. Install python-Levenshtein to remove this warning

This is a warning. The Tizonia AUR packages do not install python-Levenshtein, which is the recommended pattern matching package. At the time, I could not find this python module in the AUR. So if you find it and install it manually, this warning will go away.

I hope this helps!

**Comment by tizonia** [comment]
Closing this issue now. Please re-open if necessary.
