### ISSUE TITLE
Building on raspbian

### ISSUE THREAD

**Issue by kawomm** [tizonia/tizonia-openmax-il#619]
I'm struggeling on building on a Raspi with raspbian pi:

~/development/tizonia/tizonia-openmax-il/clients $ uname -a
Linux spotimy 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux
 the issue.

tools/tizonia-dev-build --debug --install 

leads to a configure problem:

checking for boostlib >= 1.54 (105400)... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not find a version of the library!
configure: error: ./configure failed for player

All dependencies upfront where checked.

**Comment by tizonia** [comment]
Hi!, sorry for the delayed reply and thanks for taking the time to try the software!

The first question I guess is, which version of Raspbian?. At the moment, only Raspbian Stretch is supported. Please see: https://bintray.com/tizonia/raspbian

Second question would be, are you cross-compiling or compiling natively on a Raspbian device? Tizonia has always been cross-compiled inside a chroot as compiling natively in a Raspbian device wasn't really possible due to lack the necessary amount of RAM to compile certain parts, most notably the tizonia player which uses some boost templating libraries that push the compiler quite hard in terms of memory. See https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md#known-issues

One thing I've never done is documenting properly the cross-compilation process. I shall do it soon. But you can have a look at the main script for that which is also in the tools directory. See:
https://github.com/tizonia/tizonia-openmax-il/blob/b5d3aa0d3d14211bc5c9c74154f67ef38ce4cf35/tools/tizonia-qemu-debootstrap-env#L193

This is the script that I use to cross-compile Tizonia inside a chroot and produce the binary releases that are uploaded to Bintray. This script is not for the faint of heart!. But feel free to ask anything about it.

**Comment by tizonia** [comment]
#627

**Comment by tizonia** [comment]
Closing this for now (#627 will handle the documentation needs)
