### ISSUE TITLE
Support Ubuntu Cosmic and Disco

### ISSUE THREAD

**Issue by sabrehagen** [tizonia/tizonia-openmax-il#631]
Installation on Ubuntu is only supported up to [Bionic](https://github.com/tizonia/tizonia-openmax-il/blob/09435d0c9447615d3461426e52087d7c5ec169bf/tools/install.sh#L65) which was released 18 months ago. Can you please add support for newer ubuntu distributions? Thanks!

**Comment by tizonia** [comment]
Hi!, thanks for stopping by and raising an issue. This is always appreciated.

And sorry for the delayed reply!.

Please have a look at the answer I provided to another user on this same subject.
https://github.com/tizonia/tizonia-openmax-il/issues/632#issuecomment-551264058

Basically, I usually do not provide binaries for Ubuntu versions other than the LTSs. This is just because it takes too much time and effort to build Tizonia for every new release of Ubuntu, so I only provide binaries for the LTS.

But you can use the method outlined above to install Bionic binaries on your non-LTS Ubuntu.

Another user tried that on Dingo and it worked for him. 
See:
https://github.com/tizonia/tizonia-openmax-il/pull/630

**Comment by tizonia** [comment]
I'm closing this issue as Cosmic and Disco are not LTS releases and I don't have plans to produce official deb packages for them.

The Bionic debs can be installed with the workaround documented above. Of course, the snap package may also be used on the non-LTS releases.
